bluehost/bluehost-wordpress-plugin

- bluehost.php
- inc/branding.php
- inc/menu.php
- inc/updates.php
- inc/upgrade-handler.php
- pages/mojo-performance.php
- upgrades/1.4.3.php
- upgrades/index.php
Updated name of the main plugin file. Updated plugin headers to be Bluehost branded. Added upgrade handler. Updated version to 1.4.3 (can tag at any time later) and added upgrade routine for version 1.4.3. Removed all references to the `mm_brand` option.
> Initial branding updates

- inc/updates.php
Companion PR to https://github.com/mojoness/mojo-marketplace-wp-plugin/pull/89. 
In the interest of time, pull these changes over into the Bluehost plugin. It can be separated out into a package later.
> Adding support for WordPress 5.5.

- inc/base.php
Fix issue where invalid `mm_install_date` was preventing `bh_plugin_install_date` from being set properly.
> Hotfix for date issue

- lib/.staging
The `?` was after the second parameter, not the first. The old mojo parameter was also used.
Fixes #34.
> Fix incorrect query parameter ordering.

- languages/bluehost-wordpress-plugin.pot
- package.json
- src/app/pages/home/onboarding/index.js
- src/app/pages/marketplace/product-details/index.js
FIx issue where the Husky pre-commit hook was trying to run the `i18n` npm command, but the package wasn't installed. Updated to use the existing Composer `i18n` script.
> Fix `.pot` generation

- inc/jetpack.php
Brings over some redirect logic for Jetpack connections coming from Bluerock. It includes the mojo prefixed param for back-compat until we can get it updated. It should be removed at a future date. 
This also pulls over the more current list of blocks that should not be enabled by default from the mojo plugin.
> Jetpack Updates

- bootstrap.php
Fix issue where plugin updates don't work via WP CLI
> Fix issue where plugin updates don't work via WP CLI

- assets/admin-global.css
- src/app/components/atoms/bwa-button/style.scss
- src/app/config.scss
- src/app/pages/blue-sky/index.js
- src/app/pages/help/index.js
- src/app/pages/help/style.scss
* Unify buttons to mirror Bluebird UI buttons render and transitions.
* Add some `!important` guardrails (🙈 ) to be more future-proof for Core changes.
* The Bluebird link button styles have extremely little contrast on the hover/active states and are almost impossible to distinguish.
* Buttons should only have one prop for primary vs. secondary vs. link
> Button Component: Unify frontend render

- assets/admin-global.css
- src/app/components/atoms/bwa-button/style.scss
Removes 0.08s appearance of webkit focus ring on Link Buttons that appeared on click or briefly via devtools `:active`.
> Remove flash of webkit focus ring on Link Buttons

- inc/Notifications/NotificationsRepository.php
When testing anything locally, the hardcoded hub domain in the `NotificationsRepository` class ends up causing those requests to return 401, since the local site can't connect to it. 
In the data module, I have a `BH_HUB_URL` constant that gets checked and set. This would allow a local override when testing any data/notifications using the local stack.
> Allow hub url override for local dev

- inc/RestApi/SettingsController.php
- inc/updates.php
- upgrades/2.5.0.php
WP 5.6 adds a UI element that allows site owners to opt-in to auto-updates for major version releases, and new installs will be opted-in by default.
Because the plugin was using the `allow_major_auto_core_updates` filter to implement the auto-update behavior chosen in the plugin, the text on the Core updates screen in the admin was incorrect. The core setting could also be toggled, but it would not affect the behavior of updates because of the plugin's filter.
This changes the behavior of the plugin for auto-updates on sites using WordPress 5.6 or higher to "step out of the way" to let the new code in Core manage the updates while maintaining the option that the plugin previously depended on for backwards compatibility (just in case a user downgrades their install).
> Add support for auto-updates of major versions in WP 5.6

- src/app/functions/sendPageviewEvent.js
Fixes issue where analytics URLs lacked `admin.php` and were reported as `/wp-admin/?page=bluehost` instead of `/wp-admin/admin.php?page=bluehost`.
* window.bluehostWpAdminUrl is [set via](https://github.com/bluehost/bluehost-wordpress-plugin/blob/master/inc/admin/class-assets.php#L239) `wp_localize_script()` with `admin_url()`.
> Fix Analytics: Add admin.php prefix to analytics URLs

- src/app/components/templates/bwa-base/index.js
When I added the wp.a11y.speak logic, during testing I tried to scope the code to exclude announcing the first pageload if it was the Home Page, as this effectively dupes existing screen reader behavior to announce the document title. However, subsequent route changes -- including Home Page -- should be included. I confirmed this had the desired effect on Home, but didn't check the scoping on other routes, which were now excluded.
> Fix wp.a11y logic

- inc/admin/class-assets.php
- src/app/components/organisms/bwa-common-header/index.js
- src/app/functions/index.js
- src/app/menus/user.js
- src/app/pages/blue-sky/index.js
- src/app/pages/home/sections.js
- src/app/pages/marketplace/services/index.js
* Create `getPlatformBaseUrl()` in `@app/functions` to return the proper root URL for the Bluehost Platform.
* Swap direct references for `my.bluehost.com` to use new helper function
This is a first step towards better multi-brand support in the admin application. URL references now will dynamically swap for Bluehost India's my cluster.
I spun up a Bluehost India account to validate URLs are valid in both platforms.
> Accomodate Mutliplatform URLs in Admin App

- inc/RestApi/SettingsController.php
- inc/cli/cache.php
Update file loading of wp-admin/includes/misc.php to only load when necessary. If something else (e.g. EPC) has already loaded the file, the result is an error.
> Conditionally load wp-admin/includes/misc.php only when we need to

- inc/AccessToken.php
Store the user_id which is returned when requesting a token. This is a missing piece to be able to call certain endpoints, so once we store the id, it can then be used to construct API calls where it is required.
I wonder if checking expiration is helpful here. I know it'd be more simple to just return the user here, but should we check that the token isn't expired to ensure that the user_id will be useful? Probably overthinking it here. Thoughts?
> update AccessToken class to store user_id as well

- inc/Notifications/AdminNotices.php
- inc/Notifications/NotificationsApi.php
- inc/Notifications/NotificationsRepository.php
- inc/Notifications/js/prime-notices.js
When `get_transient('bluehost_notifications')` returns `false`, instead of making request in PHP that impacts runtime, load tiny `prime-notices.js` file to hit endpoint that will make request.
> Use client-side request to prime notices transient

- inc/coming-soon.php
Bringing in a fix for jetpack subscribe functionality on the coming soon page. I spotted that this form was always failing when building the HG plugin and traced it down to a missing parameter. This commit adds the missing parameter and I've tested on a few sites that it does in fact fix the failing jetpack subscribe. 
I don't know how frequently this is used, but with the number of sites we have running the plugin, it's safe to say there are more than a handful.
> fix jetpack coming soon subscribe submission

- inc/CTB/js/ctb.js
This fixes an issue where on a successful purchase we were passing an event object instead of a node to the `dismissNotice()` method and it was throwing an error.
> Pass the correct object to dissmissNotice method

- bluehost-wordpress-plugin.php
- inc/SiteMeta.php
Some VPS servers appear to have `iconv` disabled or not installed at all. When it is not available, we can fall back to just a plain `bin2hex()` call to calculate the `site_id`. 
This would handle fewer directory name encoding edge cases, but should prevent what appears to be a more broad issue. It's also [how we used to handle it](https://github.com/bluehost/bluehost-wordpress-plugin/blob/997ca344f29d00a697f1e4a838d112f3c96614ef/inc/base.php#L148) before the `SiteMeta::get_id()` method was created.
> Add check for iconv() existence

- bluehost-wordpress-plugin.php
- inc/CTB/bootstrap.php
- inc/CTB/ctb.css
- inc/CTB/js/ctb.js
This fixes an issue where CTB success messages were disappearing immediately upon creation while trying to remove the associated notification element. 
This separates CTB modals into their own container and targets the correct notification for dismissal by searching up the DOM tree for the notification that contains the CTB trigger.
> Fix CTB notification dismissal bug

- inc/CTB/js/ctb.js
Properly set and unset 'noscroll' class to body on CTB modal open/close.
> CTB modal disabling body scroll on second open

- inc/admin-page-notifications-blocker.php
* Add remove_all_actions for all_admin_notices, admin_notices, and user_admin_notices with high specificity to override other calls.
* Kept CSS script to count for notices that get injected after DOM load.
> Remove WP Admin Notices on Bluehost pages

- composer.json
- composer.lock
- package-lock.json
- package.json
- src/app/pages/ecommerce/index.js
- src/app/store/selectors.js
This adds the eCommerce module to the plugin. Users of the plugin who are the on the eCommerce plans will be redirected to the new dashboard instead of the current `/home/onboarding` screens.
> Feature - eCommerce

- bootstrap.php
Bluehost's SSO functionality doesn't work on the first try because Yoast SEO is redirecting to their onboarding before the login actually occurs. Subsequent attempts to SSO work because the Yoast onboarding page has already been "hit" (option saved in the database even though the user never saw it because they ended up at a login screen).
This PR disables that redirect to prevent this SSO issue.
> Disable Yoast SEO onboarding redirect

- inc/Notifications/NotificationsRepository.php
There was a reference to wpscholar\Collection but it was no longer included in packages, so it was causing a fatal. This points it to the already included WP_Forge equivalent.
> update wpscholar collection reference to wp_forge collection

- inc/RestApi/CustomizeSiteController.php
- inc/RestApi/rest-api.php
- src/app/pages/home/onboarding/steps/look-right/index.js
- src/app/pages/home/sections.js
- tests/cypress/integration/home.cy.js
- tests/cypress/integration/onboarding.cy.js
Add a Rest endpoint to handle redirection to the correct editor/customizer destination based on the active theme.
Addresses: #330 
If there's a better approach to this, please let me know.
> Properly route customize site links when active theme is FSE

- bluehost-wordpress-plugin.php
- bootstrap.php
- inc/admin/class-assets.php
- inc/upgrades/2.13.2.php
Since now the .host-info file is moved to the host root we are updating the detection method.
We are also detecting using the file system instead of database check.
> Update Jarvis detection logic

- composer.json
- composer.lock
- tests/cypress/integration/z-newfold-labs/wp-module-onboarding/branding.cy.js
Release: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.4.0
> Bump onboarding version from 1.3.0 to 1.4.0

- package-lock.json
- package.json
It seems only the PHP side of ecommerce module was updated. Need to update the relevant npm version as well
> Bump ecommerce on npm to 0.8.3

- bluehost-wordpress-plugin.php
- composer.lock
Update data module to version 2.3.4 to fix fatal error on specific PHP versions when a specific cron task is run.
> Hotfix - update the data module to version 2.3.4

- src/app/components/notifications/feed.js
- src/app/index.js
- src/app/pages/ecommerce/page.js
- src/app/tailwind.pcss
As we need to show messages during flows in the plugin, this PR introduces a NotificationFeed that is placed at the top of the app. The app now has a `useNotification` hook that can be used to push messages to the feed.
```jsx
let notify = useNotification();
notify.push("woo-failure", {
title: "WooCommerce failed to install",
description: (
<span>
{__("Please try again, or contact support", "wp-module-ecommerce")}
</span>
),
variant: "error",
});
```
You can check the [StoryBook](https://ui-library.yoast.com/?path=/docs/2-components-notifications--factory) to understand more about the components.
I had to also modify the base styling set by the Yoast library to make sure the notifications did not collide with the WP Sidenav.
> Add NotificationFeed to display in-app messages

- src/app/pages/ecommerce/page.js
Add `comingSoon` controls to the ecommerce component
cc @wpalani @wpscholar
> Pass comingSoon controls to ecommerce component

- .github/workflows/cypress-matrix.yml
- .github/workflows/cypress.yml
Add a tag to replay to distinguish by brand.
> add bluehost brand to replay cypress test tag

- inc/Admin.php
- languages/wp-plugin-bluehost.pot
Bluehost.com/about-us is now bluehost.com/about. That should receive a redirect, but we should link directly to the page now.
> bluehost.com/about-us to bluehost.com/about

- src/app/pages/staging/index.js
Fix console error due to having a RadioGroup.Radio element that has both the `defaultChecked` and `checked` attributes
> Fix staging JSX errors

- package-lock.json
- src/app/components/app-nav/index.js
- src/app/components/notifications/feed.js
- tests/cypress/integration/navigation.cy.js
Somehow the nav test started failing. Looking into it clicking on a parent item, doesn't seem to always open/show the sub nav list in the test. Manual testing passes for this for me, when I click around I see the subnav right away (unless I click on the WordPress admin link for these pages, then the subnav doesn't appear). I think it has something to do with this document.click and the SubMenusManager here (https://github.com/bluehost/bluehost-wordpress-plugin/blob/main/src/app/components/app-nav/index.js#L75). I'm still not sure why it works when I click and doesn't when cypress clicks, but might be related to event bubbling up the dom and maybe it doesn't go as far when triggered by cypress.
This adds an extra click and makes the tests pass for now, but we should sort this out. It's …
> add an extra click in nav test to force nav to rerender

- .github/workflows/cypress-matrix.yml
- .github/workflows/cypress-tests-beta.yml
- .github/workflows/cypress.yml
- .github/workflows/upload-artifact-on-push.yml
- .github/workflows/upload-asset-on-release.yml
Update token used for github npm registry so we can have access to our packages in workflows.
> use newfold access token

- bootstrap.php
- inc/YoastAI.php
- inc/upgrades/3.1.1.php
This code enables Yoast AI functionality on new Yoast activations as well as existing ones.
I tested it by checking the `enable_ai_generator` value in the `wpseo` option, as well as by installing the premium plugin and verified the toggle for the feature was turned on.
> Enable 'Yoast AI' by default

- composer.json
- composer.lock
> Bump Onboarding 1.10.4

- composer.json
- composer.lock
Release Details: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.11.0
> Bump Onboarding to 1.11.0

- .distignore
- .distinclude
- composer.json
- composer.lock
Update distignore and distinclude rules to match other plugins.
Also includes compatibility update to the data module (moving PHP files from `/src` to `/includes` directory so it will not be ignored
- Upgrading newfold-labs/wp-module-data (2.4.6 => 2.4.7)
This also coincides with the how we work update here: https://github.com/newfold-labs/how-we-work/pull/22
> Update distignore and distinclude rules

- cypress.config.js
- package-lock.json
- src/app/components/section/index.js
- src/app/pages/settings/comingSoon.js
- src/app/pages/settings/index.js
- src/app/stylesheet.scss
- In the `SectionContent` component, we are adding a new optional `id` prop.
- In the `SectionContent` component, we are tracking url params and looking for `target`.
- If the value of the target param matches the passed value in the `id` prop, we'll temporarily add a blink animation.
- We are also updating the coming soon section title as per this ticket: https://jira.newfold.com/projects/PRESS1/issues/PRESS1-161
- We still need to push an update to the coming soon / ecomm modules to update the referrer link to include the URL params.
https://github.com/bluehost/bluehost-wordpress-plugin/assets/38976631/a7597509-5cdb-49ca-944b-5cecb7ec2b35
> Coming soon section flow revamp

- composer.lock
- src/app/pages/home/index.js
- tests/cypress/integration/home.cy.js
Remove (temporarily) the "Additional Features" section from the app's home page as requested by this ticket: https://jira.newfold.com/projects/PRESS1/issues/PRESS1-135
Other changes in this PR as side effects:
- Skip the "Additional Features" test in Cypress.
- Dynamically check for the site title instead of checking the static value Bluehost-WordPress-Plugin so the tests can pass everywhere.
> Remove "Additional Features" section from the app home page.

- inc/Admin.php
- tests/cypress/integration/navigation.cy.js
This PR addresses this internal ticket: https://jira.newfold.com/projects/PRESS1/issues/PRESS1-175
https://github.com/bluehost/bluehost-wordpress-plugin/assets/38976631/f4e64f9a-6ecc-4f83-bd6d-cf3b5bb7d977
> Register admin submenu exclusively outside the app

- .github/dependabot.yml
This adds our github package registry to dependabot so it can update private package dependencies too.
> add gh package registry to dependabot for npm

- composer.json
- composer.lock
This fixes Onboarding for WordPress 6.4 while ensuring backward compatibility with 6.3.
Release Notes: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.11.8
Before: Onboarding Live Previews error.
https://github.com/bluehost/bluehost-wordpress-plugin/assets/38878906/55976a73-4fd3-4423-9d33-cf34a9b876c4
After: Onboarding Live Previews work as expected.
https://github.com/bluehost/bluehost-wordpress-plugin/assets/38878906/6a2c8836-590c-4049-aad5-4fdd80e7fd19
> Bump Onboarding to 1.11.8

- .wp-env.json
- composer.json
- composer.lock
- src/app/index.js
Updates notification module with the new required method and removing the resturl constant that is no longer used.
> update notifications module

- src/app/pages/settings/automaticUpdates.js
- src/app/pages/settings/commentSettings.js
- src/app/pages/settings/contentSettings.js
Update some of the settings text to improve the grammar and make them a bit more readable
Based on comments in #820
> Update settings text

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- package-lock.json
- package.json
This release aims to fix an error with redirecting existing sites back into onboarding.
- Update plugin to version 3.7.1
- Update the onboarding module to 1.11.11
- Update the onboarding data module to 0.0.9
> Release 3.7.1

- cypress.config.js
Previously, Cypress [removed the button to run all tests](https://github.com/cypress-io/cypress/discussions/21628?ref=cypress-io.ghost.io) but have added it back under an experimental config setting, `experimentalRunAllSpecs`.
https://www.cypress.io/blog/2023/01/12/check-out-our-experimental-release-of-run-all-specs
This PR adds `experimentalRunAllSpecs: true` in `cypress.config.js`, adding:
> Add `experimentalRunAllSpecs` to run all Cypress tests

- tests/cypress/support/commands.js
When Cypress was configuing pretty permalinks it wasn't working.
The fix is to add `--hard` to the CLI command.
Additionally, the command is only run when required and confirms it has applied successfully.
Test: 
1. Use `npx wp-env destroy; npx wp-env start` to create a fresh container.
1. Visit http://localhost:8882/wp-json/ and see 404
1. Run Cypress tests
1. Visit http://localhost:8882/wp-json/ and see 200
I thought this required a `wp-cli.yml` in the container with:
```
apache_modules:
- mod_rewrite
```
but it worked ok without that. Maybe an updated to wp-env has done away with that requirement
See: https://github.com/WordPress/gutenberg/issues/49373#issuecomment-1659421165
> Fix Cypress pretty permalink setup

- inc/Admin.php
These links were already set up in the plugin but the plugin slug was incorrect in the hook so it was never loaded. This fixes that so they display (finally)
> fix plugin slug in action links filter

- cypress.config.js
Skip tests from wp-module-ecommerce which needs woocommerce installed as a pre-requisite for WordPress version <6.3 and PHP version <7.4.
Should be merged along with **Ecommerce version bump 1.3.24** [#980](https://github.com/bluehost/bluehost-wordpress-plugin/pull/980)
> Skip tests with woocommerce installation for unsupported WordPress and PHP versions

- src/app/components/app-nav/index.js
Render notifications with `'bluehost-app-nav'` context in the app navigation.
More info can be found here: https://github.com/newfold-labs/wp-module-notifications/pull/23
> Render `bluehost-app-nav` messages in the app nav

- .distignore
The plugin .zip file as downloaded from GitHub has two files that shouldn't be there: [tailwind.config.js](https://github.com/bluehost/bluehost-wordpress-plugin/blob/3.10.0/tailwind.config.js) and [postcss.config.js](https://github.com/bluehost/bluehost-wordpress-plugin/blob/3.10.0/postcss.config.js).
https://github.com/bluehost/bluehost-wordpress-plugin/releases/download/3.10.0/bluehost-wordpress-plugin.zip
I didn't actually build an archive to test it.
> Add `tailwind.config.js` and `postcss.config.js` to `.distignore`

- composer.lock
- src/app/data/help.js
Update "Events and Webinars" from the redirecting to a 404 page. Instead take the end customer to;
https://www.bluehost.com/blog/events/ 
story : https://jira.newfold.com/browse/PRESS0-1282
> bug/url changes for events and webinars - PRESS0-1282

- composer.json
- composer.lock
- package-lock.json
- package.json
- src/app/pages/settings/socialMediaAccounts.js
Following are the changes updated in ECommerce Module release 1.3.31
- PRESS0-1256 Remove text dependency, Replace text identifiers with id
- PRESS0-1248 | Suppress wp-pointer using css
- PRESS0-757 | Added translations to stripe texts
> ecommerce version bump 1.3.31

- .github/workflows/upload-asset-on-release.yml
redundant since there is a satis notice already.
It usually just sends the message "Bluehost plugin version ${GITHUB_REF#refs/tags/*} has been released!" anyways, and it also failed in the release today. Rather than tinker I think we can just remove it from this workflow.
> remove teams message from release workflow

- src/app/pages/pages-and-posts/bookingAndAppointments.js
- src/app/pages/pages-and-posts/index.js
- src/app/pages/settings/socialMediaAccounts.js
When they view Pages and Posts (launchpad) in wp-admin
Then we will have CTB for bookings instead of removing the card altogether if they dont have bookings installed.
story: https://jira.newfold.com/browse/PRESS0-1323
> bookings ctb added in pages and posts

- src/app/components/webinars-banner/index.js
- tests/cypress/integration/home.cy.js
Just removes the hard coded text from the component. The webinar title will now display exactly what the json indicates is the webinar title.
PRESS1-403
> remove 'FREE Monthly Webinar: ' line from webinar component

- src/app/pages/ecommerce/page.js
- src/app/pages/home/welcomeSection.js
Jira: https://jira.newfold.com/browse/PRESS4-547
https://github.com/bluehost/bluehost-wordpress-plugin/assets/80672694/213d8dcc-0008-474d-af15-15343f9dc66c
calling comingSoonAdminbarToggle on update of comingsoon
> Launch Button | Calling comingSoonAdminbarToggle on update of comingsoon state

- inc/Admin.php
Disable admin notices on the Plugin's App page.
Internal Ticket: https://jira.newfold.com/browse/PRESS1-303
> Disable admin notices on plugin page

- composer.json
- composer.lock
With the release of WordPress 6.6, wp-polyfill has been removed from the React script dependency. This change was preventing the Help Center modal from appearing. A fix for this is mentioned here https://make.wordpress.org/core/2024/06/25/miscellaneous-developer-changes-in-wordpress-6-6/#obsolete-polyfills-dependencies-have-been-removed.
We have manually added `regenerator-runtime` library to the Help Center as recommended by the above link.
Jira Ticket : https://jira.newfold.com/browse/PRESS0-1793
> bump Help Center to version 2.0.1

- src/app/data/routes.js
JIRA: https://jira.newfold.com/browse/PRESS0-1480
- To improve the visibility of the EcomDash plugin to our Ecommerce plus customers.
- If a customer has the Ecomdash entitlement, then the customer should see the Ecomdash landing page from the Store navigation under "Sales Channels".
- When a customer clicks on the page the first time, the CTA Get Started, it should open a new window with the Ecomdash onboarding.
- After a customer has setup the Ecomdash plugin, the customer should see the landing page with Open Dashboard as the CTA instead of the Get Started CTA.
- Related Ecommerce module [PR](https://github.com/newfold-labs/wp-module-ecommerce/pull/335)
- [Figma](https://www.figma.com/design/eKHvqb3T4Idairwe5TF29a/PRESS0-993-Ecomdash-Brand-Plugin-Integration?node-id=65-5155&t=JMlfLNHDNW …
> Adding Sales Channel route under Store main menu item

- src/app/pages/settings/wonderBlocksSettings.js
* `WonderBlocks` branding correction made in module weeks before feature toggle launched
* Copy-pasted ID fix to prevent ID duplication in DOM
> Correct misbranded spelling of WonderBlocks and DOM ID dupe

- cypress.config.js
WooCommerce minimum supported version is 6.5
> Skip eCommerce module tests on  < wp 6.5

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- cypress.config.js
- package-lock.json
- package.json
A Scheduled release for August 7. Includes the following:
- Bump Onboarding module to `2.3.9`
- Fixes some cypress tests. https://jira.newfold.com/browse/PRESS0-1823
- Bump Patterns module to 2.3.0
- Add validation to ensure label key is present before sending event to Hiive. https://jira.newfold.com/browse/PRESS0-1853
- Add search support for pattern tags. https://jira.newfold.com/browse/PRESS0-1379
- Update template tags for WonderBlocks platform to use newer templates in featured. https://jira.newfold.com/browse/PRESS0-1782
- Rework WonderBlocks library header into two distinct zones. https://jira.newfold.com/browse/PRESS0-1775
- Bump Composer/NPM deps.
N/A
> Release 3.14.1

- composer.json
- composer.lock
- cypress.config.js
This release updates the minimum compatibility of Onboarding to WP 6.5 or greater, as Onboarding uses the Wonder Theme, which has the same requirement.
> Bump Onboarding to 2.3.11

- src/app/pages/settings/contentSettings.js
Fixes `inbetween` label in settings -- should be `in between`.
> Fix typo in empty trash SelectField label

- tests/cypress/integration/help.cy.js
This PR attempts to fix the failing BH dashboard `tests/cypress/integration/help.cy.js` test for PHP 7.3 and WP 6.4.
> Fix failing BH dashboard help test

- bootstrap.php
- composer.json
- composer.lock
Moves the filter from the BH plugin's `bootstrap.php` file to the data module, where other filters are located, and includes the `is_callable` check. This approach is much safer.
> Remove the site_capabilities filter

- src/app/pages/pages-and-posts/blogPosts.js
- src/app/pages/pages-and-posts/sitePages.js
- tests/cypress/integration/pages-and-posts.cy.js
This is not-urgent, doesn't need to go into `3.14.8`, feel free to change base branch to future release.
* Appends URL query parameters to Launchpad links.
* **Does not check if WonderBlocks feature or module is active** because in the event of not being active nothing about the Core experience changes with the extra query parameters.
* Relies on [newfold-labs/wp-module-patterns@2.4.0](https://github.com/newfold-labs/wp-module-patterns/releases/tag/2.4.0) [#108](https://github.com/newfold-labs/wp-module-patterns/pull/108) to function.
**Post**: wp-admin/post-new.php?wb-library=patterns&wb-category=text
**Page**: wp-admin/post-new.php?post_type=page&wb-library=patterns&wb-category=features
https://github.com/user-attachments/assets/095f2805-fa01-406c-ba14-5280d45026bc …
> PRESS0-2200: Update add new post and page launchpads with wb params

- src/app/components/errorCard/index.js
- src/app/pages/home/myProductsSection.js
- src/app/pages/settings/commentSettings.js
- src/app/pages/settings/contentSettings.js
Some files that were touched by the 3.14.11 release had linting issues that snuck through. It seems to be a new rule since the files were last touched, but this fixes them. 
The fix involves using sprintf for strings with vars rather than stitching strings manually with spaces.
> Fix lint issues with i18n strings

- bluehost-wordpress-plugin.php
- inc/alt-experience/init.php
- `define`s are moved to be able to use them in the alt-experience file and to make them fit in better with the rest
- condensed the comments of the loading
- enqueued the styles rather than just echoing the CSS
> Update burst safety mode page to enqueue CSS rather than just echoing it

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- languages/wp-plugin-bluehost.pot
- package-lock.json
- package.json
This uses the re-released installer module `v 1.2.1` that has a fix for the version mismatch. 
PR for fix: https://github.com/newfold-labs/wp-module-installer/pull/41
Release Notes: https://github.com/newfold-labs/wp-module-installer/releases/tag/1.2.1
> Bump Installer Module to `v1.2.1`

- composer.json
- composer.lock
Now that onboarding has updated the performance module version in its requirements we can remove the alias to the 2.x major update.
> remove performance module alias

- src/app/util/helpers.js
Problem: The `isJarvis` Check that is defined in the **helper util** function checks for https://github.com/bluehost/bluehost-wordpress-plugin/blob/b12e1d7c561c1047293b9e95c5bf14c2814ca00d/src/app/util/helpers.js#L226 before sending the actual capability data and the way this function is defined is it returns the actual value itself and not 'if the key exists in the capabilities' [Reference](https://github.com/newfold-labs/wp-module-runtime/blob/c63ba65520c917a9be99a492bc824f4a54c2daef/src/index.js#L5-L7) 
Due to this even if the **isJarvis** capability is **_switched off_** in a prod site, the `isJarvis function` returned **true**, as the if case inside the function fails and the default return is true.
This created an issue where in **Bluehost_India** customers the link to **Bluehost …
> Fix 'isJarvis' check that always returned true

- src/app/pages/settings/index.js
Adds IDs to settings sections to be able to link to them using the `nfd-target` param.
Before only one of these links works:
- ✅ https://example.com/wp-admin/admin.php?page=bluehost&nfd-target=coming-soon-section#/settings
- ❌ https://example.com/wp-admin/admin.php?page=bluehost&nfd-target=content-section#/settings
After they both work:
- ✅ https://example.com/wp-admin/admin.php?page=bluehost&nfd-target=coming-soon-section#/settings
- ✅ https://example.com/wp-admin/admin.php?page=bluehost&nfd-target=content-section#/settings
> Add IDs to settings sections

- .github/workflows/create-milestones.yml
Currently, our automated workflow that creates a milestone each week has an inaccurate description. This patch fixes the description to use the correct date that PRs should be submitted by, which is one week before the release date.
> Update description to mention PR due date is a week before

- inc/alt-experience/init.php
This change is required to implement all changes implemented on this [PR](https://github.com/newfold-labs/wp-module-performance/pull/41) for the module "Performance".
- [] Linting and tests pass locally with my changes
> New: include new burst safety folder
