- inc/checkout.php
- inc/user-experience-tracking.php
Removed Google tracking and brought touched files up to coding standards.
> Remove Google Tracking

- inc/jetpack.php
I assume we want to merge this in here as well @MikeHansenMe ?
> Unregister MailChimp block from JetPack

- inc/admin/class-page.php
- inc/coming-soon.php
First pass, not tested on a local.
> First pass at menu bubble.

- composer.json
- composer.lock
- src/app/components/atoms/bwa-button/index.js
- src/app/components/organisms/bwa-header/mobile-sidebar/index.js
- src/app/components/organisms/bwa-header/style.scss
- src/app/components/organisms/bwa-header/user-menu.js
- Update to Gutenframe module 0.1.3 (removes the reference to `MM_BASE_URL`).
- Fixes forwardRef warning for buttons.
- Change out invalid attribute name
- Add URL for fetching validation token
- Fix user menu styles
> Plugin updates

- inc/cli/staging.php
- inc/staging.php
- lib/.staging
> Copy over staging changes from mojo plugin.

- composer.json
- composer.lock
- inc/staging.php
Simply adds the new data module to the plugin. 
We should treat this PR as a review of that code as well:
https://github.com/bluehost/endurance-wp-module-data
> Add Data Module

- compat/scan.php
Fix issue in compatibility scan where it is incorrectly checking if the Mojo plugin is active.
> Fix safe mode

- composer.json
- composer.lock
- inc/staging.php
This reverts commit 675e453529c4bfa8f4b363fbf35931a7d2bfcc38.
Back out the data module commit for now. We'll redo it later this week after we tag.
> Revert "Add Data Module (#31)"

- lib/.staging
This should be an ampersand since it is appended to other existing query params.
> Fix issue on staging

- composer.lock
Change composer.lock to use latest version of data module
> Bump data module version to 1.0.1

- inc/admin.php
- lib/.staging
A quick fix to redirect users to the staging page.
> Fix staging redirect issue

- composer.lock
> Bump data module to 1.0.2

- lib/.staging
Convert ampersand to question mark
> Minor staging fix

- bluehost-wordpress-plugin.php
- inc/AccessToken.php
- inc/ResponseUtilities.php
- languages/bluehost-wordpress-plugin.pot
Update code to avoid refreshing access token on ajax requests. Log errors instead of failing silently.
> Updates for AccessToken logic

- bluehost-wordpress-plugin.php
- bootstrap.php
- composer.lock
- languages/bluehost-wordpress-plugin.pot
- upgrades/2.2.2.php
- upgrades/2.2.3.php
Update the data module to v1.2 and bump the plugin to v2.2.3
> Update Data module to 1.2

- composer.json
- composer.lock
> Remove spam prevention module

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- inc/RestApi/AdminErrorController.php
- inc/RestApi/rest-api.php
- inc/Staging.php
- languages/bluehost-wordpress-plugin.pot
Minor update to the data module
> Update data module and dependencies

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- languages/bluehost-wordpress-plugin.pot
Fixes composer issue with PHP versions < 7.2
> Disable platform check

- bootstrap.php
- inc/LoginRedirect.php
Automatically redirect users to the Bluehost dashboard on login if a redirect URL hasn't already been set.
> Login redirect

- languages/bluehost-wordpress-plugin.pot
- package-lock.json
- package.json
- src/app/app.scss
- src/app/pages/blue-sky/index.js
- src/app/pages/blue-sky/style.scss
- src/app/pages/help/index.js
- src/app/pages/help/style.scss
- src/app/styles/react-player.scss
- tests/cypress/integration/blue-sky.spec.js
- tests/cypress/integration/help.spec.js
- Make video image clickable and load the YouTube video when clicked (on both Help & Blue Sky)
- Update external links to open in a new tab
- Ensure that phone number links show the phone number
- Update tests
> Help/Blue Sky Page Updates

- languages/bluehost-wordpress-plugin.pot
- package-lock.json
- package.json
- src/app/components/atoms/bwa-button/index.js
- src/app/components/molecules/bwa-error/index.js
- src/app/components/organisms/bwa-header/index.js
- src/app/components/organisms/bwa-header/mobile-sidebar/index.js
- src/app/components/organisms/bwa-header/user-menu.js
- src/app/functions/get.js
- src/app/functions/index.js
- src/app/pages/help/index.js
- src/app/pages/home/hosting/index.js
- src/app/pages/home/onboarding/index.js
- tests/cypress/integration/header.spec.js
- tests/cypress/integration/help.spec.js
- tests/cypress/integration/home.spec.js
- tests/cypress/integration/onboarding.spec.js
Add UTM params to all external links.
> Add UTM params to all external links

- .github/workflows/lint.yml
- bluehost-wordpress-plugin.php
- bootstrap.php
- composer.json
- composer.lock
- inc/Notifications/AdminNotices.php
- inc/Notifications/Notification.php
- inc/Notifications/NotificationsApi.php
- inc/Notifications/NotificationsRepository.php
- inc/Notifications/bootstrap.php
- inc/Notifications/dismiss-notices.js
- inc/updates.php
- languages/bluehost-wordpress-plugin.pot
- package-lock.json
- package.json
- phpcs.xml
- src/app/components/organisms/bwa-notification/index.js
- src/app/components/organisms/index.js
- src/app/components/templates/bwa-marketplace/index.js
- src/app/pages/home/index.js
- src/app/pages/home/onboarding/index.js
- src/app/pages/settings/index.js
- src/app/pages/tools/staging/index.js
- src/app/store/actions.js
- src/app/store/reducer.js
- src/app/store/selectors.js
Implement a notifications system for the WordPress admin and the Bluehost pages.
> Notifications

- bluehost-wordpress-plugin.php
* Notifications #62 
* Help & Blue Sky Page Updates #60 
* Add UTM to all external links #64 
* Buttons Component: Unify frontend render #61 
* Login Redirect #59 
* Add help to WP Admin Bar #58
> Version bump to 2.4.0

- inc/Notifications/Notification.php
- languages/bluehost-wordpress-plugin.pot
Update the notification dismissal endpoint to include the notification ID.
> Fix incorrect notifications API endpoint

- composer.lock
- package-lock.json
This updates the `composer.lock` file to be compatible with Composer 2.
Steps to update the file:
- Run `composer update` with Composer 2 installed.
Additionally, this updates the `package-lock.json` file with changes from running `npm install` and `npm audit fix`.
> Composer npm updates

- .github/workflows/cypress.yml
- .github/workflows/lint.yml
- .github/workflows/upload-artifact-on-push.yml
- .github/workflows/upload-asset-on-release.yml
- bluehost-wordpress-plugin.php
- composer.lock
- inc/Notifications/bootstrap.php
- languages/bluehost-wordpress-plugin.pot
Add the `plugin_search` key to the events that clear the notifications cache.
> Update notifications cache clearing keys

- src/app/pages/help/search-results/index.js
Adds utm parameters to the resource center cards using our internal helper function.
> Add utm parameters to Resources cards on Help Page

- pages/coming-soon.php
Mega PR to fix any remaining non-translated strings in the plugin.
> Ensure all strings are translated

- package.json
* Adds npm scripts for creating zip similar to how the runner does.
* Reports zip filesize to console.
> Add command to simulate GitHub Runner build

- bluehost-wordpress-plugin.php
- inc/coming-soon.php
- inc/pages/coming-soon.php
- languages/bluehost-wordpress-plugin.pot
- package.json
- tests/cypress/integration/coming-soon.spec.js
- tests/cypress/support/commands.js
Fix the issue where the coming soon page was fatal erroring.
> Fix the coming soon page

- bluehost-wordpress-plugin.php
- composer.lock
Update the Bluehost plugin updater package.
> Update the Bluehost plugin updater package

- bootstrap.php
Repair file path for UpgradeHandler to glob upgrade routines.
> Correct path to upgrade routines passed to UpgradeHandler

- src/app/pages/settings/performance/index.js
Update copy for cache settings to match what is actually happening.
> Update cache descriptions to match EPC

- src/app/components/organisms/bwa-route-contents/index.js
- src/app/pages/marketplace/plugins/index.js
- src/app/pages/marketplace/services/index.js
- src/app/pages/marketplace/themes/index.js
- src/app/pages/yoast-seo-premium/index.js
- src/app/pages/yoast-seo-premium/style.scss
- src/app/pages/yoast-woocommerce-seo/index.js
- src/app/pages/yoast-woocommerce-seo/style.scss
- tests/cypress/integration/plugins.spec.js
- tests/cypress/integration/yoast-seo-premium.spec.js
- tests/cypress/integration/yoast-woocommerce-seo.spec.js
* Adds Yoast SEO Marketplace pages for Premium and WooCommerce.
* Fixes duplicated shim products when re-sorting marketplace after first render.
> Yoast SEO Premium & Yoast WooCommerce SEO

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
Plugin release PR:
Bump plugin version to 2.8.5
Updating the data module to 1.8
> version bump and update data module package @1.8

- composer.json
- composer.lock
- inc/base.php
This updates to the latest data module @1.8.2 and adds the new install date filter now used in the data module. 
See https://github.com/bluehost/endurance-wp-module-data/pull/27
> update data module and add new install date filter

- src/app/components/molecules/bwa-product-card/index.js
- src/app/pages/marketplace/services/index.js
- tests/cypress/integration/services.spec.js
Add Lendio and adjustments to the Product Card to accomodate.
> Add Lendio to Services Page

- .github/workflows/cypress.yml
- composer.json
- composer.lock
This introduces the secure password module to the plugin.
For ongoing development of this module (including bugs and potential features), see https://github.com/bluehost/wp-module-secure-passwords.
> Add the secure passwords module.

- src/app/components/organisms/bwa-common-header/desktop-dropdown/index.js
- src/app/pages/yoast-seo-premium/index.js
- src/app/pages/yoast-woocommerce-seo/index.js
> Fix "class=" to "className=" in some React files.

- inc/admin/class-assets.php
This PR adds the Customer Bluehost data into the window.bluehost object.
> Inject Customer information into the window

- inc/CTB/CTBApi.php
Add/ensure that `site_id` and `customer_id` values are available and sent with CTB requests.
> Add site id to data

- inc/CTB/js/ctb.js
Ensure that notification is dismissed after a CTB is purchased.
> Move notice dismissal to purchase success

- src/app/pages/marketplace/style.scss
Marketplace page CSS styles and responsiveness enhancements
> Update marketplace page styles

- README.md
This adds the steps we discussed today to a quick list on the main plugin readme file. Should be easy to follow them for releases in the future. I tried to add any relevant links to point future us in the right direction in case we run into any issues. Please read through them to make sure I didn't forget anything. Preview in branch: https://github.com/bluehost/bluehost-wordpress-plugin/tree/add/release-notes
I also updated the logo image since the old one was broken and added more badges so we can better see status of the latest build, lint and tests.
The only issue I see is that in an .md file like this, the checkboxes are not interactive, so not much point in having them here. It was a nice thought though.
> fix image src, add release steps and more badges

- .github/workflows/cypress.yml
Debugging Replay on top of #175
> add list to action

- src/app/pages/help/index.js
Fix broken video embed for bluesky video on help page.
> update url for embedded bluesky video

- src/app/pages/marketplace/style.scss
Visual enhancements to the TabPanel component
* make its design more consistent with the rest of the marketplace/bluehost
* improvements to mobile experience
* other updates to marketplace cards (prevent elements overlapping at different breakpoints)
Summary: https://www.berrycast.com/conversations/5062c3d1-c1c3-53be-a9b8-f36c241fd0f3
> Marketplace TabPanel styles update

- src/app/pages/marketplace/style.scss
- update the marketplace width to be more fluid with 3 cards on lg-screens > 1024px.
- horizontal  TabPanel filter.
- Update media skeleton loading animation to apply on the div rather than img.
> Marketplace 3 cards wide

- inc/menu.php
- Add Marketplace "Premium" link to WP Themes filter bar.
- Add Marketplace "Premium" link to WP Plugins filter bar.
> Add Marketplace links to WP Themes/Plugins

- composer.json
- composer.lock
- package-lock.json
- package.json
MMP Final Version bump for eCommerce Module
> Update module version for MMP

- .distignore
Adds rules to wildcard exclude paths from being included in `.distignore` used by rsync to generate final build.
> Update .distignore: Exclude development files from Newfold Labs deps

- composer.json
- composer.lock
Adds `newfold-labs/wp-module-onboarding@0.0.1` to the Bluehost Plugin.
_Note that the date gate here will block Module Activation -- returning `true` early before that logic should get everything testable for now._
https://github.com/newfold-labs/wp-module-onboarding/blob/trunk/includes/ModuleController.php#L70
> Add wp-module-onboarding to bluehost-wordpress-plugin

- composer.json
- composer.lock
> bump onboarding module

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
Bugfixes for customer data and checking if a user is an e-commerce customer.
> Version 2.12.1

- bluehost-wordpress-plugin.php
- composer.lock
composer upgrade bluehost/bluehost-wp-customer-data
> Release 2.12.2

- composer.json
- composer.lock
- package-lock.json
- package.json
> Update eCommerce to v0.4.7

- .github/workflows/cypress-matrix.yml
- .github/workflows/cypress.yml
- .github/workflows/upload-artifact-on-push.yml
- .github/workflows/upload-asset-on-release.yml
This updates the setup-node action to the latest version. The `cache` property can now be used to allow the action to handle caching of dependencies on its own allowing two other steps to be removed from workflows.
> Update the `setup-node` action

- composer.json
- composer.lock
> update onboarding to 0.2.1

- composer.json
- composer.lock
- package-lock.json
- package.json
- src/app/components/organisms/bwa-route-contents/index.js
- src/app/pages/ecommerce/index.js
- src/app/pages/home/index.js
- tests/cypress/integration/newfold-labs/wp-module-onboarding/steps/basic-info.cy.js
Updated with new Version of the eCommerce Module.
> Bump ecommerce module

- bluehost-wordpress-plugin.php
- composer.lock
- inc/AccessToken.php
- inc/upgrades/2.12.7.php
(draft PR for now since we don't have the customer module released yet to include here)
Prepping for a release that updates the customer data module. 
Adds an upgrade routine that will clear throttle values (option and transient) when updating to the latest customer data module since it fixes a throttle bug.
> update customer data module

- composer.lock
> bump customer data module to 1.4.6

- composer.json
- composer.lock
> upgrade onboarding from 0.2.1 to 0.2.2

- composer.json
- composer.lock
- package-lock.json
- package.json
> Bump eCommerce Module to v0.5.0

- composer.json
- composer.lock
> Bump onboarding to 0.2.4

- composer.json
- composer.lock
- package-lock.json
- package.json
> Ecommerce bump - v0.5.1

- composer.json
- composer.lock
Release Details: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/0.2.5
> bump onboarding to 0.2.5

- inc/Themes.php
* Adds "Premium Themes" and "Upload Theme" admin menu links to Appearance.
* Adds Upload Theme Page.
* Adds Premium Themes" and "Upload Theme" buttons to themes.php header.
* Modifies WordPress "Add New Theme" button text to "WordPress.org Themes" in themes.php header.
> Add Premium Themes menu link and header buttons

- .wp-env.json
- composer.json
- composer.lock
- package-lock.json
- package.json
- tests/cypress/integration/coming-soon.cy.js
- tests/cypress/integration/onboarding.cy.js
> update ecom module for new coming soon module

- inc/RestApi/SettingsController.php
- inc/user-experience-tracking.php
- lib/.staging
reference new coming soon value for site status
keep old value in sync with a hook
> Fix remaining mm_coming_soon usage

- bluehost-wordpress-plugin.php
- composer.lock
Update customer data module and bump version
> Update customer data module and bump version

- .github/workflows/cypress-matrix.yml
- .github/workflows/cypress.yml
- .github/workflows/lint.yml
- .github/workflows/satis-webhook.yml
- .github/workflows/upload-artifact-on-push.yml
- .github/workflows/upload-asset-on-release.yml
Updates GitHub Actions to fix deprecated `::set-output` instances
> Update GitHub Actions to fix deprecated `::set-output` instances

- .github/workflows/cloudflare-clear-cache.yml
- package-lock.json
- package.json
Currently, we're using an outdated version of the Replay Cypress dependency. The new version provides advanced UI around debugging tests from a CLI / prod environment.
> Update Replay dependency

- composer.json
- composer.lock
- tests/cypress/integration/newfold-labs/wp-module-onboarding/phase-2-rudimentary.cy.js
- tests/cypress/integration/newfold-labs/wp-module-onboarding/steps/basic-info.cy.js
Release v1.0.0: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.0.0
Release v1.0.1: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.0.1
> bump onboarding to 1.0.0

- composer.json
- composer.lock
- package-lock.json
- package.json
> Bump ecommerce module version to 0.6.2

- composer.json
- composer.lock
Release: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.0.3
> bump onboarding to 1.0.3

- inc/CTB/CTBApi.php
> fix outdated customer data reference for CTB

- composer.json
- composer.lock
Release: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.0.4
> bump onboarding to 1.0.4

- inc/admin.php
- tests/cypress/integration/widget.cy.js
> don't add the dashboard widget or enqueue the assets

- inc/CTB/CTBApi.php
> fix second reference to customer collect

- composer.json
- composer.lock
- package-lock.json
- package.json
> Ecommerce version update

- composer.json
- composer.lock
- inc/menu.php
This update will upgrade the Marketplace Module to 1.4.8 to bring the latest premium plugins marketplace in plugin-install.php features. Also it removes "Premium" from plugins sub menu since this will be handled in the Marketplace going forward.
> Update Marketplace Module to 1.4.8

- package-lock.json
- package.json
- tests/cypress/integration/notifications.cy.js
Update Cypress to latest 12.4.1
> Update/cypress again - 12.4.1

- .github/workflows/cypress-matrix.yml
- .github/workflows/cypress.yml
Implement logic to allow tests to run for Dependabot PRs automatically
> Implement logic to allow tests to run for Dependabot PRs automatically

- .github/workflows/cypress-matrix.yml
> fix strict equals in matrix workflow

- composer.json
- composer.lock
Release: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.1.1
> bump onboarding to 1.1.1

- composer.json
- composer.lock
Release: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.1.2
> bump onboarding to 1.1.2

- bluehost-wordpress-plugin.php
Adding brand to the container so modules can rely on the value from the container from now on. This is loaded from mm_brand for now but will give us a single source of truth for the brand and set us up better to manage it.
> add brand to container

- composer.json
- composer.lock
> bump onboarding to 1.2.2

- src/app/pages/ecommerce/index.js
- src/app/pages/home/index.js
- src/app/store/selectors.js
As we're moving to open up the eCommerce experience to all users, we need a better way of evaluating all the options the user is entitled to in the eCommerce experience. 
This PR adds new `ecommerce capabilities` logic instead of relying on multiple booleans.
The current supported capabilities. Each of these capabilities denote a certain entitlement of the eCommerce experience.
- experience
- standard | premium | minimal `(These are variants)`
- upgrade
- The user can be auto directed to the eCommerce experience on loading the plugin.
- Allows users to install/manage Newfold YITH Plugins 
- Everything above
- Access to additional plugin. ex. Ecomdash
- No access to Newfold YITH Plugins.
- Is given option to buy YITH plugins from marketplace.
- The user is currently not suited to use the …
> Add eCommerce capabilities

- bluehost-wordpress-plugin.php
- bootstrap.php
- inc/admin/class-assets.php
- src/app/functions/index.js
- src/app/menus/user.js
- src/app/pages/home/sections.js
This code detects if the hosting platform is Jarvis-based, if true, it routes the app my-account links to the proper destination.
> Jarvis platform my-accounts links

- src/app/functions/index.js
- src/app/menus/user.js
- src/app/pages/home/sections.js
> Update Jarvis links detection method

- cypress.config.js
> Conditionally exclude Onboarding tests for WordPress versions < 6.1

- .github/workflows/cypress-matrix.yml
> automatically run matrix on release branch PRs

- composer.json
- composer.lock
Release: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.4.1
> Bump Onboarding to 1.4.1

- .github/workflows/cypress-tests-beta.yml
Created a new workflow for cypress tests to run on latest beta/RC WordPress releases, to make sure the cypress tests run on latest WordPress releases.
> Create Cypress Beta Only Tests Workflow

- composer.json
- composer.lock
- tests/cypress/integration/z-newfold-labs/wp-module-onboarding/steps/sitetype-secondary.cy.js
- tests/cypress/integration/z-onboarding-phase-2-rudimentary.cy.js
Release: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.6.0
This release mainly implements the site classification API and also stores selections in new primary and secondary options, using the helpers written in the data module(v2.3.3).
> bump onboarding to 1.6.0

- .distinclude
- .github/workflows/cypress-matrix.yml
- .github/workflows/cypress-tests-beta.yml
- .github/workflows/cypress.yml
- .github/workflows/upload-artifact-on-push.yml
- .github/workflows/upload-asset-on-release.yml
- package.json
A potential solution to including the static JSON file in the data module. I wasn't able to test the `Build Plugin` workflow on my fork, so can't say that it works for sure.
> Include static json file from the data module

- src/app/pages/ecommerce/index.js
This passes the newer MarketplaceLite to the ecommerce module.
> Pass MarketplaceLite to ecommerce

- composer.json
- composer.lock
- package-lock.json
- package.json
- src/app/data/routes.js
- src/app/pages/ecommerce/page.js
- src/app/pages/ecommerce/styles.scss
The eCommmerce module is still the older version, but this setups the shell for the new changes to be worked on.
> Integrate Store page and use ecommerce module

- composer.json
- composer.lock
- package-lock.json
- package.json
Bumps [newfold-labs/wp-module-ecommerce](https://github.com/newfold-labs/wp-module-ecommerce) to 0.9.0.
> Bump newfold-labs/wp-module-ecommerce to 0.9.0

- composer.json
- composer.lock
- cypress.config.js
> Bump onboarding to 1.7.0

- composer.lock
- package-lock.json
- package.json
> Bump to latest version of wp-module-ecommerce feature branch

- composer.json
- composer.lock
- package-lock.json
- package.json
eCommerce module now uses @newfold-labs/wp-module-installer for managing plugin installation instead of onboarding APIs
> Bump newfold-labs/wp-module-ecommerce to 0.9.1

- src/app/components/notifications/feed.js
- src/app/tailwind.pcss
Also, added additional props in `notify.push` to be compliant with the actual component.
cc @wpalani @wpscholar
> Fix focus ring for text inputs

- src/app/pages/home/helpCard.js
- src/app/pages/home/index.js
- src/app/pages/home/welcomeSection.js
- tests/cypress/integration/home.cy.js
Adding simple home tests for now so there's something to start with once complete.
> cypress home tests in ui update

- src/app/pages/settings/contentSettings copy.js
- src/app/pages/settings/contentSettings.js
- src/app/pages/settings/index.js
- src/app/tailwind.pcss
- tests/cypress/integration/settings.cy.js
we are disabling tests for now, until we figure out a streamlined way of testing the components
> Add content settings section

- composer.json
- composer.lock
- package-lock.json
- package.json
Bump newfold-labs/wp-module-ecommerce to v0.10.1-rc-2
> Bump newfold-labs/wp-module-ecommerce to v0.10.1-rc-2

- package-lock.json
- package.json
- src/app/pages/ecommerce/page.js
> Bump ecommerce 

- composer.json
- composer.lock
> update help module to 1.0.3

- composer.json
- composer.lock
- package-lock.json
- package.json
This is the final release of wp-module-ecommerce before the launch.
> Bump @newfold-labs/wp-module-ecommerce to v1.0.0

- composer.json
- composer.lock
- package-lock.json
- package.json
Updates the ecommerce package to 1.0.2
> update ecommerce module to 1.0.2

- bootstrap.php
> add plugin icon and banner for update and detail screens

- bootstrap.php
- inc/LoginRedirect.php
- This class was missed after migration to 3.x
- Also catching an edge case where users are not getting redirected to the App after getting to the login page from /wp-admin instead of /wp-login
> Add login redirect class

- .github/workflows/upload-artifact-on-push.yml
> check version in build workflow

- package-lock.json
- package.json
> Bump newfold-labs/wp-module-ecommerce to 1.0.6

- composer.json
- composer.lock
Bumps Help Center, helps restrict the number of calls to algolia by conditionally rendering the component via a capability check.
> bump help center

- .distinclude
> re-add missed include for `site-classification.json`

- composer.json
- composer.lock
> bump onboarding to 1.8.3

- src/app/components/app-nav/index.js
- src/app/pages/performance/performance.js
> Fix react missing key console error

- src/app/components/site-info/index.js
- point to proper authenticated path
> #550 Fix Bluehost Account Link

- src/app/components/site-info/index.js
Fixes Jarvis urls
Credit: https://github.com/bluehost/bluehost-wordpress-plugin/pull/551
> Jarvis urls

- tests/cypress/integration/z-newfold-labs/wp-module-onboarding/2-general-onboarding-flow/basic-info.cy.js
- tests/cypress/integration/z-newfold-labs/wp-module-onboarding/3-ecommerce-onboarding-flow/get-started-welcome.cy.js
> Skip exit to wordpress tests

- src/app/components/site-info/index.js
Update View Site to View Store for the Store page and all of the subpages within Store for users who have WooCommerce installed- then redirect user to their shop page instead of their homepage.
If WooCommerce is not installed, the CTA should remain as "View Site" and redirect user to the home page
- When the woocommerce is installed and in the store page. The button will show as view store and will redirect to shop page when click on the button
- When the woocommerce is not installed and in the store page. the button will show as view site and will redirect to home page when click on the button
- When the page is in the home tab. The button will show as view site and will redirect to home page
> PRESS4-287 | Store | Update View Site to View Store

- src/app/data/routes.js
- Added Payments section for the navigation in the store page, when woocommerce is installed
> PRESS4-303 | Added payments tab in store

- inc/Admin.php
This addresses the fatal error that was reported in #638 
We were able to reproduce the issue only after installing the "WP Mega Menu" plugin: https://wordpress.org/plugins/wp-megamenu/
The plugin has the following message in the plugin directory: "This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress." 
The plugin also has the following message upon activation: "The plugin generated 1697 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin."
Having the file only included once though is best practice and …
> load `Data.php` via `include_once` in `add_to_runtinme`

- composer.json
- composer.lock
https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.11.3
> Fixes skeletion loading issue in Onboarding

- src/app/components/app-nav/logo.js
This PR addresses this internal ticket: https://jira.newfold.com/projects/PRESS1/issues/PRESS1-177
Fix: add width and height classes to the `Brand` component (logo) to fix the logo not showing on browsers that require explicit width value on svgs.
> Fix Bluehost logo not appearing on Safari

- composer.json
- composer.lock
This updates the global ctb module to the latest version 1.0.5 which fixes an issue with the API endpoint path containing a typo.
> update global ctb module to 1.0.5

- src/app/pages/home/accountCard.js
Update account card links and labels for Jarvis.
> update account links and labels for jarvis

- src/app/data/routes.js
https://jira.newfold.com/browse/PRESS4-372
Showing Sales & discounts based on ``canAccessGlobalCTB``
Attaching the pr link from ``Ecommerce`` as they are related to each other.
https://github.com/newfold-labs/wp-module-ecommerce/pull/153
> PRESS4-372 || Create CTB Trigger for Commerce CTB

- bootstrap.php
Add `&nfd-target=coming-soon-section#/settings` to the coming soon admin notice to display the blink animation introduced in [V3.4](https://github.com/bluehost/bluehost-wordpress-plugin/pull/706)
This PR aims to address this internal ticket: https://jira.newfold.com/projects/PRESS1/issues/PRESS1-191
> Update coming soon admin notice link to include query strings

- composer.json
- composer.lock
https://github.com/bluehost/bluehost-wordpress-plugin/assets/38878906/67468023-e207-405f-bdd7-a445e708417f
https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.11.6
> Bump Onboarding to 1.11.7

- .github/dependabot.yml
> remove all assignees and reviewers from dependabot PRs

- package-lock.json
- package.json
- src/app/components/site-info/index.js
> add @wp/decodeEntities and use to ensure site title is properly decoded

- bluehost-wordpress-plugin.php
- composer.lock
- package.json
Updates the patterns module to version 0.1.13 to fix a CSS bug with pattern preview rendering.
> Pending 3.8.2 release

- assets/styles/coming-soon.css
- bootstrap.php
Ticket: https://jira.newfold.com/browse/PRESS4-461
> Added links to Coming Soon page

- composer.json
- composer.lock
- cypress.config.js
Release Notes:
https://github.com/newfold-labs/wp-module-onboarding/releases/tag/2.1.4
> Bump Onboarding to `2.1.4`

- composer.json
- composer.lock
fixes conflict with wonder blocks button and greedy styles in coming soon
> update coming soon module to 1.2.3

- composer.json
- composer.lock
- cypress.config.js
https://github.com/newfold-labs/wp-module-onboarding/releases/tag/2.1.6
> Bump Onboarding to 2.1.6

- composer.json
- composer.lock
> Add activation module package

- src/app/data/routes.js
Update "Sales & Discounts" naming to "Sales & Promotions"
story : https://jira.newfold.com/browse/PRESS4-514
> Updating "Sales & Discounts" naming to "Sales & Promotions"

- composer.json
- composer.lock
https://github.com/newfold-labs/wp-module-onboarding/releases/tag/2.1.8
https://github.com/newfold-labs/wp-module-onboarding-data/releases/tag/1.1.5
> Bump Onboarding to 2.1.8

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- package-lock.json
- package.json
Release 3.9.4 updates the data, patterns, and SSO modules.
> Release 3.9.4

- composer.json
- composer.lock
> Update Onboarding to 2.3.0

- composer.json
- composer.lock
- package-lock.json
- package.json
* `Press0-1122` by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/281
* `PRESS0-1157 | Next Steps in BH Dashboard` by @ramyakrishnai in https://github.com/newfold-labs/wp-module-ecommerce/pull/284
* `PRESS0-1164 | Adding events to next steps` by @manikantakailasa  in https://github.com/newfold-labs/wp-module-ecommerce/pull/284
* `Press0-1119 | Press0-1141` by @mamatharao05 in https://github.com/newfold-labs/wp-module-ecommerce/pull/291
* `PRESS0-1201` by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/296
* `Version update 1.3.30` by @ramyakrishnai in https://github.com/newfold-labs/wp-module-ecommerce/pull/299
> Update eCommerce version bump and lock files updated

- composer.json
- composer.lock
1. Adds Cypress Tests for the Migration Screens
2. Change of Placeholder text in the Input Field of the Site Details Step in the AI Sitegen Flow
3. Correction of an Event Tracking Issue in the Migration Step: This event was not being tracked and reported to the Events API
> Update Onboarding to 2.3.1

- composer.json
- composer.lock
> Update Onboarding to 2.3.2

- composer.json
- composer.lock
- package-lock.json
- package.json
Downgrading the facebook module since, the required changes are not done from onboarding yet.
> downgrade facebok changes

- composer.json
- composer.lock
https://github.com/newfold-labs/wp-module-onboarding/releases/tag/2.3.3
> Bump Onboarding to 2.3.4

- composer.json
- composer.lock
Should fix failing tests merged caused by `1.2.0`
> Bump deactivation module to 1.2.1

- composer.json
- composer.lock
Bump data module version to `2.5.3` which adds new tests and [other changes](https://github.com/newfold-labs/wp-module-data/releases/tag/2.5.3)
> Bump data module version to 2.5.3

- tests/cypress/integration/home.cy.js
Replace references to old values in `NewfoldRuntime`
story: - PRESS0-1213
> Replace references to old values in `NewfoldRuntime`

- composer.json
- composer.lock
- package-lock.json
- package.json
- PRESS0-1673 | Fix multiple tests failing in all brand release PRs cypress tests and matrix workflows. by @sangeetha-nayak in https://github.com/newfold-labs/wp-module-ecommerce/pull/334
- eCommerce version bump 1.3.36 by @ramyakrishnai in https://github.com/newfold-labs/wp-module-ecommerce/pull/337
> ecommerce version bump 1.3.36

- composer.json
- composer.lock
Bump sso module to latest version
> Update sso module to 1.0.6

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- package-lock.json
- package.json
Revert Data module from 2.6.0 to 2.5.3.
2.6.0 was found to be causing a problem with the host's WordPress installer.
> Release 3.13.3

- .wp-env.json
- composer.json
- composer.lock
- package-lock.json
- package.json
PRESS0-1480 : Add Sales channel page to promote Ecomdash plugin adoption by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/335
Ecommerce version bump 1.3.38 by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/335
> Ecommerce version bump 1.3.38

- composer.json
- composer.lock
- package-lock.json
- package.json
* [PRESS0-1482](https://jira.newfold.com/browse/PRESS0-1482) : Add Google Analytic Elements/tags to Store page by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/342
* Ecommerce module version bump 1.3.40 by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/343
> Update/ecommerce version bump 1.3.40

- composer.lock
> Bump Survey to 1.0.1

- bluehost-wordpress-plugin.php
- composer.json
- composer.lock
- package-lock.json
- package.json
Out-of-cycle release. Includes the following:
- Update migration module to 1.0.10
- Add query params by @ramyakrishnai in https://github.com/newfold-labs/wp-module-migration/pull/61
- Add/press0-1877 && P3 fixes by @ramyakrishnai in https://github.com/newfold-labs/wp-module-migration/pull/62
- Update survey module to 1.0.1
- Fix assets include issue.
> Release 3.14.5

- composer.json
- composer.lock
- package-lock.json
- package.json
Ecommerce Version bump to 1.3.43 includes bugfix for [PRESS0-1968](https://jira.newfold.com/browse/PRESS0-1968)
> Update/ecommerce version 1.3.43

- inc/alt-experience/index.html
- src/app/data/routes.js
PRESS0-2122 | Updated Help Text in Side Nav Menu to open Helpcenter
> PRESS0-2122 | Updated Help Text in Side Nav Menu to open Helpcenter

- languages/wp-plugin-bluehost.pot
Updated the POT file so the build file paths are updated to the lastet release version.
> updated the POT file to the latest version

- composer.json
- composer.lock
- package-lock.json
- package.json
- Move capabilities check behind init and is_admin
> ecommerce version bump to 1.3.44

- composer.json
- composer.lock
Fix Onboarding Sentry Issues by @officiallygod in https://github.com/newfold-labs/wp-module-onboarding/pull/620
Release Notes: https://github.com/newfold-labs/wp-module-onboarding/releases/tag/2.4.2
> Onboarding Release bump to 2.4.2

- src/app/data/routes.js
- src/app/pages/wpsolutions/index.js
- src/app/pages/wpsolutions/style.scss
JIRA: https://jira.newfold.com/browse/PRESS0-1723
- Given a customer has a "WordPress Solutions Entitlement"
- When they are in the branded plugin
- Then there is a new top level navigation called "My Plugins & Tools"
- And we list the plugins/tools that the customer is entitled to as per the solution they have purchased.
> WP Admin | Branded Plugin | Solutions Entitlements Page

- inc/Admin.php
- src/app/data/routes.js
- src/app/pages/solutions/index.js
Solutions module bug fixes:
- [PRESS0-2277](https://jira.newfold.com/browse/PRESS0-2277)
- [PRESS0-2282](https://jira.newfold.com/browse/PRESS0-2282)
> Bug Fixes Solutions module

- src/app/pages/home/accountCard.js
Fix alignment issue in accountCard for smaller screens.
> Small screen alignment fix for accountCard - PRESS0-2276

- composer.json
- composer.lock
This module is no longer used, this removes it as a dependency.
See: https://github.com/newfold-labs/wp-module-my-products/pull/11
> remove my products module

- composer.json
- composer.lock
> update help center module version

- composer.json
- composer.lock
https://github.com/user-attachments/assets/b156749f-9766-4798-862e-5697d60a1bb7
This branch introduce the option "Skip 404" in the Performance module. Before of this change the option was available only on WordPress settings area.
Adds a new option to selective exclude caching for certain pages.
> Bump Performance to 2.3.0

- composer.json
- composer.lock
Minor changes to enable a couple features by default:
https://github.com/newfold-labs/wp-module-performance/pull/72
https://github.com/newfold-labs/wp-module-performance/pull/74
> Bump Performance to 2.4.1

- composer.json
- composer.lock
This requirement came from the vendor team as part of efforts to improve migration stability in the long term. We are basically updating their helper package to the latest version and ensuring our code is compatible with it. @circlecube, please let me know if we can include this in the January 29th release? Thanks!
PR: https://github.com/newfold-labs/wp-module-migration/pull/73
> Bump Migration to 1.1.0
